name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [9.6, 10, 11, 12]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: "Install base deps"
        run: yarn install
      - name: "Run linter"
        run: yarn run eslint:lint
      - name: "Install yarn deps"
        run: yarn run bootstrap
      - name: "Build app"
        run: yarn run build
      - name: "Run tests"
        run: yarn run test
        env:
          TEST_DB_HOST: 127.0.0.1
          TEST_DB_PASSWORD: postgres
          TEST_DB_USER: postgres
          TEST_DB_NAME: cms_test
          TEST_DB_NAME_TENANT: cms_test_tenant
          TEST_DB_PORT: 5432
