name: Publish
on:
  push:
    tags:
      - '**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get the version
        run: echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: "Install base deps"
        run: yarn install
      - name: "Install yarn deps"
        run: yarn run bootstrap
      - name: "Build app"
        run: yarn run build
      - name: "Publish NPM"
        run: bash ./scripts/npm/publish.sh
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: "Publish Docker"
        run: bash ./scripts/docker/publish.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
